### PR TITLE
Fix suggestions with multiple corrections

### LINKED ISSUE #81: `Style/MethodDefParentheses` creates a suggestion with just one opening parenthese
The closing parenthese `)` remains missing in the suggestion.

image

### PR DESCRIPTION
**Pull request by mfittko**
The suggestions feature is broken as it's ignoring any offenses with multiple corrections. This is leading to wrong or - at best - incomplete sugggestions.

Fixes https://github.com/reviewdog/action-rubocop/issues/81 and https://github.com/reviewdog/action-rubocop/issues/96

Examples (before fix):
Screenshot 2024-11-04 at 13 48 14
Screenshot 2024-11-04 at 16 56 14

Examples (with fix):
Screenshot 2024-11-04 at 16 45 18
image

### CODE REVIEW

**Comment by mfittko** [comment]
We're using this branch now as we think that the change is working well. Unfortunately this is not well covered by tests (yet) though, so if someone is able to help ot there, feel free to reach out.

**Comment by mfittko** [comment]
@haya14busa I think I fixed the issue and verified with a local devcontainer setup (see PR #130 )

**Comment by mfittko** [comment]
can we trigger the workflows again? we're using this for 2 weeks now for most of our repos without a problem and we would like to see this in upstream

File: rdjson_formatter/rdjson_formatter.rb [hunk 1]
```diff
@@ -90,23 +90,44 @@ def build_range(offense)
   # @param [RuboCop::Cop::Offense] offense
   # @return [Array{Hash}]
   def build_suggestions(offense)
```
Comment (javierjulio) [inline rdjson_formatter/rdjson_formatter.rb:92]: This has two Rubocop metrics based warnings since it's a larger method now. Perhaps determining the positions/range and sorted corrections could each be extracted into a private method?

We don't see to have tests for this other than integration tests through Rubocop CLI. If its easier to write a unit test that would be fine but is there anyway we could update the test data with samples that would trigger the warnings before this change and then include it here to demonstrate that the fix is working as expected?

**Comment by pavelsavva** [comment]
What would it take to get this merged? Seeing the same issue with parentheses.

CleanShot 2025-02-21 at 22 00 20@2x

**Comment by jakeonfire** [comment]
would this also fix `Style/StringLiteralsInInterpolation` suggestions?
Screenshot 2025-06-02 at 5 29 29 PM

**Comment by jakeonfire** [comment]
does any `reviewdog` maintainer want to pick up the torch on this? it would fix a lot of issues with inline suggestions. 🙏

**Comment by pavelsavva** [comment]
I've had this PR into @mfittko's fork fixing the tests... I think it should be a complete, ready-to-merge fix.

https://github.com/sofatutor/action-rubocop/pull/1

**Comment by mfittko** [comment]
I merged the PR, sorry for letting this wait for so long, my bad. Thanks for the polishing @pavelsavva

**Comment by pavelsavva** [comment]
> I merged the PR, sorry for letting this wait for so long, my bad. Thanks for the polishing @pavelsavva 

Haha no worries, I figured it wasn't a priority. Fingers crossed all the tests should be good to go now🤞

**Comment by jakeonfire** [comment]
all checks green, can we get this merged and versioned? 🙏

**Comment by haya14busa** [comment]
Can you write tests? https://github.com/reviewdog/action-rubocop/blob/master/test/rdjson_formatter/test.sh

**Comment by jakeonfire** [comment]
test coverage for offense with multiple corrections: https://github.com/sofatutor/action-rubocop/pull/3

mind merging @mfittko?

**Comment by mfittko** [comment]
@jakeonfire I merged, but something seems off, did not try it out myself, sorry.

**Comment by jakeonfire** [comment]
@mfittko shoot - you'll have to delete those [extra rubocop rules i added](https://github.com/sofatutor/action-rubocop/pull/3/files#diff-4f894049af3375c2bd4e608f546f8d4a0eed95464efcdea850993200db9fef5c). for some reason they are logged as missing and pass when included locally, but it seems the test harness here uses an older rubocop. mind doing that?

**Comment by jakeonfire** [comment]
or i can do it - just merge https://github.com/sofatutor/action-rubocop/pull/4 @mfittko

**Comment by mfittko** [comment]
Tests are green, from my side we can merge then, shall I? Can someone approve?

**Comment by haya14busa** [comment]
Thanks!
